### ISSUE TITLE
Game crashes at random times (Render thread problem)

### ISSUE THREAD

**Issue by PrestonHager** [homchom/recode#52]
The game hangs and then crashes at seemingly random times. Minecraft's launcher only gives the information of `Process crashed with exit code -805306369`. When looking at the error log the following error is found:

```
Uncaught exception in thread "Render thread"
io.github.homchom.recode.event.RequestTimeoutException
	at io.github.homchom.recode.event.TrialRequester$requestFrom$2.invokeSuspend(DetectorImpl.kt:165)
	at io.github.homchom.recode.shaded.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.github.homchom.recode.shaded.kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at io.github.homchom.recode.shaded.kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at io.github.homchom.recode.shaded.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.github.homchom.recode.shaded.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at io.github.homchom.recode.RecodeDispatcher.expedite(RecodeDispatcher.kt:43)
	at io.github.homchom.recode.event.FlowEvent.run(EventImpl.kt:72)
	at io.github.homchom.recode.render.RenderBlockEntitiesEvent.run(RenderEvents.kt)
	at net.minecraft.class_761.runBlockEntityEvents(class_761.java:4437)
	at net.minecraft.class_761.redirect$zkh000$recode$interceptChunkBlockEntities(class_761.java:4428)
	at net.minecraft.class_761.method_22710(class_761.java:1337)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: io.github.homchom.recode.shaded.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@729eafbf, io.github.homchom.recode.RecodeDispatcher$taskLoop$1@30d06bf2]
```

I cannot find a simple way to reproduce this bug.

I have tried increasing allocated memory, but it has not helped. Other GitHub issues seem to point to an incorrect Java version?

**Comment by homchom** [comment]
> I have tried increasing allocated memory, but it has not helped. Other GitHub issues seem to point to an incorrect Java version?

This bug was introduced in the most recent beta, it is known, and unfortunately these things will not fix it. There's basicaly nothing one can do to work around it; I hope to have another beta out today or tomorrow with a fix for this.

**Comment by homchom** [comment]
This was fixed in betas 6 and 7, but I forgot to close this :)
