### ISSUE TITLE
Minecraft Crashes before loading Loading Screen [Linux, 1.18.2]

### ISSUE THREAD

**Issue by EvilsSouls** [homchom/recode#9]
I have the latest (0.1.0-beta.3) version of the mod. 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 8/22/22, 6:30 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: 'void io.github.homchom.recode.shaded.org.newsclub.net.unix.NativeUnixSocket.connect(java.lang.String, java.io.FileDescriptor)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:136)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:107)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:98)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:46)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at io.github.homchom.recode.mod.features.discordrpc.DFDiscordRPC.connect(DFDiscordRPC.java:59)
	at io.github.homchom.recode.mod.features.discordrpc.DFDiscordRPC.update(DFDiscordRPC.java:74)
	at io.github.homchom.recode.mod.events.impl.LegacyChangeStateEvent.run(LegacyChangeStateEvent.java:23)
	at io.github.homchom.recode.mod.events.impl.LegacyChangeStateEvent.lambda$new$0(LegacyChangeStateEvent.java:12)
	at io.github.homchom.recode.event.RHookKt.hookListenerOf$lambda-0(RHook.kt:19)
	at io.github.homchom.recode.event.RHook.invoke(RHook.kt:24)
	at io.github.homchom.recode.sys.networking.DFState.notifyStateChange(DFState.java:356)
	at io.github.homchom.recode.sys.networking.DFState$CurrentState.setMode(DFState.java:413)
	at net.minecraft.client.MinecraftClient.handler$fbe000$setScreen(MinecraftClient:24448)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:637)
	at net.minecraft.client.main.Main.main(Main:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:136)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:107)
	at io.github.homchom.recode.shaded.org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:98)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:46)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at io.github.homchom.recode.shaded.com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at io.github.homchom.recode.mod.features.discordrpc.DFDiscordRPC.connect(DFDiscordRPC.java:59)
	at io.github.homchom.recode.mod.features.discordrpc.DFDiscordRPC.update(DFDiscordRPC.java:74)
	at io.github.homchom.recode.mod.events.impl.LegacyChangeStateEvent.run(LegacyChangeStateEvent.java:23)
	at io.github.homchom.recode.mod.events.impl.LegacyChangeStateEvent.lambda$new$0(LegacyChangeStateEvent.java:12)
	at io.github.homchom.recode.event.RHookKt.hookListenerOf$lambda-0(RHook.kt:19)
	at io.github.homchom.recode.event.RHook.invoke(RHook.kt:24)
	at io.github.homchom.recode.sys.networking.DFState.notifyStateChange(DFState.java:356)
	at io.github.homchom.recode.sys.networking.DFState$CurrentState.setMode(DFState.java:413)
	at net.minecraft.class_310.handler$fbe000$setScreen(class_310.java:24448)
	at net.minecraft.class_310.method_1507(class_310.java)
	at net.minecraft.class_310.<init>(class_310.java:637)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.10.0-14-amd64
	Java Version: 17.0.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 233645520 bytes (222 MiB) / 958398464 bytes (914 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Picasso
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 2944.40
	Virtual memory used (MB): 4094.09
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		advancedchatbox: AdvancedChatBox 1.18-1.1.3
			com_carrotsearch_hppc: hppc 0.9.0
			edu_washington_cs_knowitall_opennlp-chunk-models: opennlp-chunk-models 1.5
			edu_washington_cs_knowitall_opennlp-postag-models: opennlp-postag-models 1.5
			edu_washington_cs_knowitall_opennlp-tokenize-models: opennlp-tokenize-models 1.5
			javax_measure_unit-api: unit-api 2.1.3
			javax_xml_bind_jaxb-api: jaxb-api 2.3.1
			net_loomchild_segment: segment 2.0.3
			net_sf_trove4j_trove4j: trove4j 3.0.3
			org_apache_opennlp_opennlp-tools: opennlp-tools 1.9.3
			org_carrot2_morfologik-fsa: morfologik-fsa 2.1.7
			org_carrot2_morfologik-fsa-builders: morfologik-fsa-builders 2.1.7
			org_carrot2_morfologik-speller: morfologik-speller 2.1.7
			org_carrot2_morfologik-stemming: morfologik-stemming 2.1.7
			org_jetbrains_intellij_deps_trove4j: trove4j 1.0.20200330
			org_languagetool_language-en: language-en 5.5
			org_languagetool_languagetool-core: languagetool-core 5.5
			tech_units_indriya: indriya 1.3
			tech_uom_lib_uom-lib-common: uom-lib-common 1.1
		advancedchatcore: AdvancedChatCore 1.18.2-1.5.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_github_darkkronicle_konstruct_addons: addons 2.0.3-build1
			com_github_darkkronicle_konstruct_core: core 2.0.3-build1
			io_github_maowimpl_owo: owo 2.0.0
			kommandlib: KommandLib 0.1.0-1.18.1
			org_apache_commons_commons-csv: commons-csv 1.8
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 4.4.2
		advancedchatfilters: AdvancedChatFilters 1.18.2-1.2.3
			org_javadelight_delight-nashorn-sandbox: delight-nashorn-sandbox 0.2.5
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
			org_webjars_bower_js-beautify: js-beautify 1.9.0
		advancedchathud: AdvancedChatHUD 1.18.2-1.3.2
		advancedchatlog: AdvancedChatLog 1.18.2-1.2.1
		advancedchatmacros: AdvancedChatMacros 1.18.2-1.0.0
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		amecs: Amecs 1.3.8+mc.1.18.2
		animatica: Animatica 0.4+1.18
		antighost: AntiGhost 1.18.2-fabric0.47.10-1.1.4
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.5.76
		axolotlbuckets: Axolotl Buckets 1.0.0
		betterblockoutline: BetterBlockOutline 1.4.2-1.18.1
		bettercommandblockui: BetterCommandBlockUI 0.1.0
		bettermounthud: Better Mount HUD 1.1.4
		borderlessmining: Borderless Mining 1.1.2+1.18.2
		brb: Better Recipe Book 1.5.6
		bundle_jumble: Bundle Jumble 1.0.0-mc1.18.2
		capes: Capes 1.3.1+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.69
		carpet-extra: Carpet Extra 1.4.72
		carpet-fixes: Carpet Fixes 1.18.x-1.7.11
			conditional-mixin: conditional mixin 0.3.1
		carpet-tctc-addition: Carpet TCTC Addition 2.0.177+d21bda9-beta
			carpet-tctc-addition-1_18_2: Carpet TCTC Addition for 1.18.2 2.0.177+d21bda9-beta
		cem: Custom Entity Models 0.7.1
			completeconfig: CompleteConfig 1.0.0
		citresewn: CIT Resewn 1.1.0+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.0+1.18.2
		clientcommands: Client Commands 2.6.6
			clientarguments: clientarguments 1.3.1
			clientcommands-scripting: Clientcommands Scripting 1.3.2
			multiconnect-api: MultiConnect API 1.5.10
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		colormatic: Colormatic 3.1.1+mc.1.18.2
		continuity: Continuity 2.0.0+1.18.2
		coord_book: Coordinate Book 1.1.0
		couplings: Couplings 1.8.0+1.18.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		dailydad: Daily Dad 1.3.2
		dcch: DCCH 2.0+1.17
		debugify: Debugify 1.11.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		detailab: Detail Armor Bar 2.6.2+1.18-fabric
		dfscript: DFScript 29
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.8
		elementa: Elementa 531
		emi: EMI 0.2.0+1.18.2
		enhancedblockentities: Enhanced Block Entities 0.7+1.18.2
		entity_texture_features: Entity Texture Features 3.1.4-mc1.18.x
		entityculling: EntityCulling-Fabric 1.5.1
		essential: Essential 4479+ge389e52d8
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		essential-dependencies: Essential Dependencies 0
		extrasounds: ExtraSounds 2.3.1+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
			soundcategories: Sound Categories 1.2.4+1.18
		fabric: Fabric API 0.56.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.5+22138a0260
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.1+0ca3bd2b60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fabrishot: Fabrishot ${version}
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		ferritecore: FerriteCore 4.2.1
		fvt: Flour's Various Tweaks 1.10.1-mc1.18.2
		ibeeditor: IBE Editor 2.1.1
		indium: Indium 1.0.6+mc1.18.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		isometric-renders: Isometric Renders 0.3.1+1.18
			worldmesher: Worldmesher 0.2.10+1.18
		isxander-main-menu-credits: Main Menu Credits 1.0.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		jukeboxparticles: Jukebox Particles 1.0.0
		lambdabettergrass: LambdaBetterGrass 1.2.4+1.18
			spruceui: SpruceUI 3.3.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
		languagereload: Language Reload 1.2.1
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		magiclib: MagicLib 0.5.37
			magiclib-1_18_2: MagicLib for 1.18.2 0.5.37
		malilib: MaLiLib 0.12.1
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 3.2.2
		morechathistory: MoreChatHistory 1.1.0
		mousewheelie: Mouse Wheelie 1.10.1+mc1.18.2
			amecsapi: Amecs API 1.3.6+mc22w06a
			coat: Coat 1.0.0-beta.18+mc1.18.2
			tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		nicerportals: Nicer Portals 1.0.0
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_annotations: annotations 13.0
		puzzle: Puzzle 1.3.0
			midnightlib: MidnightLib 0.4.0
			puzzle-base: Puzzle Base 1.3.0
			puzzle-gui: Puzzle GUI 1.3.0
			puzzle-models: Puzzle Models 1.3.0
			puzzle-splashscreen: Puzzle Splash Screen 1.3.0
		recode: recode 0.1.0-beta.3
			javax_websocket_javax_websocket-api: javax.websocket-api 1.1
			libgui: LibGui 5.4.0+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.18.2-build.42
		resounding: Resounding 1.0.0-bc.9
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.5+mc1.18.2-build.42
			caffeineconfig: CaffeineConfig 1.1.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		stendhal: Stendhal 1.3.3-1.18
		tooltipfix: ToolTip Fix 1.0.4-1.18
		tweakeroo: Tweakeroo 0.13.3
		universalcraft: UniversalCraft 225
		vigilance: Vigilance 252
		villagerconverting: Villager Converting 1.0.1
			roundalib: RoundaLib 0.1.8
		visiblebarriers: Visible Barriers 1.18.2-fabric-1.5.0
		yosbr: YOSBR 0.1.1
		zoomify: Zoomify 1.6.0
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: (off)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.10.0-14-amd64, LLVM 12.0.1) GL version 4.6 (Core Profile) Mesa 21.3.8 (git-813ee839be), AMD
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), recode (recode)

**Comment by Electric131** [comment]
Try reading the FAQ first :) it is helpful and this is one of the Q&As:
Q: recode crashes on startup! What do I do?
A: If recode crashes with a org.newsclub.net.unix.AFUNIXSocketException or an UnsatisfiedLinkError, it is probably related to the current Discord RPC feature (which we intend to replace with a more stable replacement). It is disabled by default in the next beta, but for now there are two workarounds:

1. Manually disable Discord RPC in the mod's config file at .minecraft/config/recode.json. It is a JSON, so it should look something like this:
{
  "discordRPC": false
}

2. Use a different, supported JVM, one that doesn't crash. For example, Temurin JDKs do not work.

If you get a startup crash with something else, ask in issues.

**Comment by homchom** [comment]
With that said, this issue hadn't hadn't posted on GitHub yet, so it's fine. Thanks for posting.

**Comment by homchom** [comment]
@Electric131 The FAQ is only on the Discord server atm, so although I know this wasn't the case here, try not to assume people on GitHub have read the FAQ, especially since there's no indication on this repo anywhere to "read the FAQ".

**Comment by Electric131** [comment]
Well that is why I decided to also put the answer here if they couldn't/haven't read the FAQ
